# Basic dependabot.yml file with
# minimum configuration for two package managers

version: 2
updates:
  # Enable version updates for Gradle
  - package-ecosystem: "gradle"
    # Look for `build.gradle` in the `root` directory
    directory: "/"
    # Check for updates once daily
    schedule:
        interval: "daily"

  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
      time: '04:00'
    open-pull-requests-limit: 10
    ignore:
      # ignore Maven APIs/SPIs
      - dependency-name: org.apache:maven:*
      # ignore Java 8+ dependencies
      - dependency-name: org.mockito:mockito-core
        versions:
          - ">= 3.0"
      - dependency-name: org.apache.commons:commons-lang3
        versions:
          - ">= 3.9"
      - dependency-name: commons-io:commons-io
        versions:
          - ">= 2.7"
      # Ignore Maven 3.2.1+
      - dependency-name: org.apache.maven.plugin-testing:maven-plugin-testing-tools
        versions:
          - ">=3.2.0"
      - dependency-name: org.apache.maven.plugin-testing:maven-plugin-testing-harness
        versions:
          - ">=3.2.0"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
