language: java
sudo: false
jdk:
  - oraclejdk8
  - oraclejdk11
  - openjdk8
  - openjdk11
install: true
script:
#  ./gradlew verify -x sign
  ./gradlew build -x sign
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
# safelist
branches:
  only:
  - develop
  - master
  - /^feature_.*$/
notifications:
  email: false
