kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-jenkins-home
  namespace: jenkins
spec:
  #storageClassName: aws-efs
  storageClassName: nfs-provisioner
  #storageClassName: manual
  accessModes:
  -  ReadWriteMany
  #-  ReadWriteOnce  # volume can be mounted as read-write by many nodes.
 resources:
    requests:
      storage: 10Gi
