apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: jenkins
  labels:
    app: jenkins-master
spec:
  # type: NodePort
  type: LoadBalancer
  selector:
    app: jenkins-master
  ports:
    - name: http-port
      port: 80
      targetPort: 8080
      #protocol: TCP
    - name: agent
      port: 50000
      targetPort: 50000
      #protocol: TCP
