# This workflow will build a Java project with Docker

name: Docker Workflow

on:
  push:
    #branches: [master]
    branches-ignore: "dependabot/**"
    paths-ignore:
      - "**.md"
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened]
    paths-ignore:
      - "**.md"

jobs:
  build:
    name: Build Docker
    #runs-on: ubuntu-18.04
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
          cache: maven

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          #tags: nabla/jenkins-pipeline-scripts:latest,nabla/jenkins-pipeline-scripts:${{ github.sha }}
          tags: nabla/jenkins-pipeline-scripts:latest
#      - name: Run Trivy vulnerability scanner
#        uses: aquasecurity/trivy-action@master
#        with:
#          image-ref: 'nabla/jenkins-pipeline-scripts:${{ github.sha }}'
#          format: 'table'
#          exit-code: '1'
#          ignore-unfixed: true
#          vuln-type: 'os,library'
#          severity: 'CRITICAL,HIGH'
